### ISSUE TITLE
Create Git Issue Templates

### ISSUE THREAD

**Issue by healthhackersER** [healthhackersER/CAMA-Module-Angular-8-Template#1]
- [x] BUG
- [x] FEATURE
- [x] Other

@see https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

**Comment by healthhackersER** [comment]
https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

**Comment by GundlackFelixDEV** [comment]
Done - Issue Templates Working
